CREATE TABLE IF NOT EXISTS team (
    name VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    team_name VARCHAR(255) REFERENCES team(name)
);

CREATE TABLE IF NOT EXISTS pull_request (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    merged_at TIMESTAMP WITH TIME ZONE NULL,

    author_id VARCHAR(255) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS pr_reviewer (
    request_id VARCHAR(255) REFERENCES pull_request(id) ON DELETE CASCADE,
    reviewer_id VARCHAR(255) REFERENCES users(id),

    PRIMARY KEY (request_id, reviewer_id)
);
